name: clone_discord
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.3.7
  go_router: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - asset/fonts/
  #   - images/a_dot_ham.jpeg
  fonts:
   - family: GGSans
     fonts:
       - asset: asset/fonts/gg_sans_Regular.ttf
       - asset: asset/fonts/gg_sans_Semibold.ttf
         weight: 600
       - asset: asset/fonts/gg_sans_Bold.ttf
         weight: 700
       - asset: asset/fonts/gg_sans_Medium.ttf
         weight: 500
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
